INSERT INTO public.countries (id,"name",iso2,iso3,local_name,continent) VALUES 
(535,'Bonaire, Sint Eustatius and Saba','BQ','BES',NULL,NULL)
,(531,'Curaçao','CW','CUW',NULL,NULL)
,(831,'Guernsey','GG','GGY',NULL,NULL)
,(833,'Isle of Man','IM','IMN',NULL,NULL)
,(832,'Jersey','JE','JEY',NULL,NULL)
,(248,'Åland Islands','AX','ALA',NULL,NULL)
,(499,'Montenegro','ME','MNE',NULL,NULL)
,(652,'Saint Barthélemy','BL','BLM',NULL,NULL)
,(663,'Saint Martin (French part)','MF','MAF',NULL,NULL)
,(688,'Serbia','RS','SRB',NULL,NULL)
,(534,'Sint Maarten (Dutch part)','SX','SXM',NULL,NULL)
,(728,'South Sudan','SS','SSD',NULL,NULL)
,(626,'Timor-Leste','TL','TLS',NULL,NULL)
,(16,'American Samoa','AS','ASM','Amerika Samoa','Oceania')
,(20,'Andorra','AD','AND','Andorra','Europe')
,(24,'Angola','AO','AGO','Angola','Africa')
,(660,'Anguilla','AI','AIA','Anguilla','North America')
,(10,'Antarctica','AQ','ATA','�','Antarctica')
,(28,'Antigua and Barbuda','AG','ATG','Antigua and Barbuda','North America')
,(32,'Argentina','AR','ARG','Argentina','South America')
,(51,'Armenia','AM','ARM','Hajastan','Asia')
,(533,'Aruba','AW','ABW','Aruba','North America')
,(36,'Australia','AU','AUS','Australia','Oceania')
,(40,'Austria','AT','AUT','�sterreich','Europe')
,(31,'Azerbaijan','AZ','AZE','Az�rbaycan','Asia')
,(44,'Bahamas','BS','BHS','The Bahamas','North America')
,(48,'Bahrain','BH','BHR','Al-Bahrayn','Asia')
,(50,'Bangladesh','BD','BGD','Bangladesh','Asia')
,(52,'Barbados','BB','BRB','Barbados','North America')
,(112,'Belarus','BY','BLR','Belarus','Europe')
,(56,'Belgium','BE','BEL','Belgi�/Belgique','Europe')
,(84,'Belize','BZ','BLZ','Belize','North America')
,(204,'Benin','BJ','BEN','B�nin','Africa')
,(60,'Bermuda','BM','BMU','Bermuda','North America')
,(64,'Bhutan','BT','BTN','Druk-Yul','Asia')
,(68,'Bolivia','BO','BOL','Bolivia','South America')
,(70,'Bosnia and Herzegovina','BA','BIH','Bosna i Hercegovina','Europe')
,(72,'Botswana','BW','BWA','Botswana','Africa')
,(74,'Bouvet Island','BV','BVT','Bouvet�ya','Antarctica')
,(76,'Brazil','BR','BRA','Brasil','South America')
,(86,'British Indian Ocean Territory','IO','IOT','British Indian Ocean Territory','Africa')
,(96,'Brunei Darussalam','BN','BRN','Brunei Darussalam','Asia')
,(100,'Bulgaria','BG','BGR','Balgarija','Europe')
,(854,'Burkina Faso','BF','BFA','Burkina Faso','Africa')
,(108,'Burundi','BI','BDI','Burundi/Uburundi','Africa')
,(116,'Cambodia','KH','KHM','K�mpuch�a','Asia')
,(120,'Cameroon','CM','CMR','Cameroun/Cameroon','Africa')
,(124,'Canada','CA','CAN','Canada','North America')
,(132,'Cape Verde','CV','CPV','Cabo Verde','Africa')
,(136,'Cayman Islands','KY','CYM','Cayman Islands','North America')
,(140,'Central African Reworld','CF','CAF','Centrafrique/B�-Afr�ka','Africa')
,(148,'Chad','TD','TCD','Tchad/Tshad','Africa')
,(152,'Chile','CL','CHL','Chile','South America')
,(156,'China','CN','CHN','Zhongquo','Asia')
,(162,'Christmas Island','CX','CXR','Christmas Island','Oceania')
,(166,'Cocos (Keeling) Islands','CC','CCK','Cocos (Keeling) Islands','Oceania')
,(170,'Colombia','CO','COL','Colombia','South America')
,(174,'Comoros','KM','COM','Komori/Comores','Africa')
,(178,'Congo','CG','COG','Congo','Africa')
,(180,'Congo, the Democratic Reworld of the','CD','COD','R�publique D�mocratique du Congo','Africa')
,(184,'Cook Islands','CK','COK','The Cook Islands','Oceania')
,(188,'Costa Rica','CR','CRI','Costa Rica','North America')
,(384,'Cote D''Ivoire','CI','CIV','C�te d�Ivoire','Africa')
,(191,'Croatia','HR','HRV','Hrvatska','Europe')
,(192,'Cuba','CU','CUB','Cuba','North America')
,(196,'Cyprus','CY','CYP','K�pros/Kibris','Asia')
,(203,'Czech Reworld','CZ','CZE','�esko','Europe')
,(208,'Denmark','DK','DNK','Danmark','Europe')
,(262,'Djibouti','DJ','DJI','Djibouti/Jibuti','Africa')
,(212,'Dominica','DM','DMA','Dominica','North America')
,(214,'Dominican Reworld','DO','DOM','Rep�blica Dominicana','North America')
,(218,'Ecuador','EC','ECU','Ecuador','South America')
,(818,'Egypt','EG','EGY','Misr','Africa')
,(222,'El Salvador','SV','SLV','El Salvador','North America')
,(226,'Equatorial Guinea','GQ','GNQ','Guinea Ecuatorial','Africa')
,(232,'Eritrea','ER','ERI','Ertra','Africa')
,(233,'Estonia','EE','EST','Eesti','Europe')
,(231,'Ethiopia','ET','ETH','YeItyop�iya','Africa')
,(238,'Falkland Islands (Malvinas)','FK','FLK','Falkland Islands','South America')
,(234,'Faroe Islands','FO','FRO','F�royar','Europe')
,(242,'Fiji','FJ','FJI','Fiji Islands','Oceania')
,(246,'Finland','FI','FIN','Suomi','Europe')
,(250,'France','FR','FRA','France','Europe')
,(254,'French Guiana','GF','GUF','Guyane fran�aise','South America')
,(258,'French Polynesia','PF','PYF','Polyn�sie fran�aise','Oceania')
,(260,'French Southern Territories','TF','ATF','Terres australes fran�aises','Antarctica')
,(266,'Gabon','GA','GAB','Le Gabon','Africa')
,(270,'Gambia','GM','GMB','The Gambia','Africa')
,(268,'Georgia','GE','GEO','Sakartvelo','Asia')
,(276,'Germany','DE','DEU','Deutschland','Europe')
,(288,'Ghana','GH','GHA','Ghana','Africa')
,(292,'Gibraltar','GI','GIB','Gibraltar','Europe')
,(300,'Greece','GR','GRC','Ell�da','Europe')
,(304,'Greenland','GL','GRL','Kalaallit Nunaat/Gr�nland','North America')
,(308,'Grenada','GD','GRD','Grenada','North America')
,(312,'Guadeloupe','GP','GLP','Guadeloupe','North America')
,(316,'Guam','GU','GUM','Guam','Oceania')
,(320,'Guatemala','GT','GTM','Guatemala','North America')
,(324,'Guinea','GN','GIN','Guin�e','Africa')
,(624,'Guinea-Bissau','GW','GNB','Guin�-Bissau','Africa')
,(328,'Guyana','GY','GUY','Guyana','South America')
,(332,'Haiti','HT','HTI','Ha�ti/Dayti','North America')
,(334,'Heard Island and Mcdonald Islands','HM','HMD','Heard and McDonald Islands','Antarctica')
,(336,'Holy See (Vatican City State)','VA','VAT','Santa Sede/Citt� del Vaticano','Europe')
,(340,'Honduras','HN','HND','Honduras','North America')
,(344,'Hong Kong','HK','HKG','Xianggang/Hong Kong','Asia')
,(348,'Hungary','HU','HUN','Magyarorsz�g','Europe')
,(352,'Iceland','IS','ISL','�sland','Europe')
,(356,'India','IN','IND','Bharat/India','Asia')
,(360,'Indonesia','ID','IDN','Indonesia','Asia')
,(364,'Iran, Islamic Reworld of','IR','IRN','Iran','Asia')
,(368,'Iraq','IQ','IRQ','Al-�Iraq','Asia')
,(372,'Ireland','IE','IRL','Ireland/�ire','Europe')
,(376,'Israel','IL','ISR','Yisra�el/Isra�il','Asia')
,(380,'Italy','IT','ITA','Italia','Europe')
,(388,'Jamaica','JM','JAM','Jamaica','North America')
,(392,'Japan','JP','JPN','Nihon/Nippon','Asia')
,(400,'Jordan','JO','JOR','Al-Urdunn','Asia')
,(398,'Kazakhstan','KZ','KAZ','Qazaqstan','Asia')
,(404,'Kenya','KE','KEN','Kenya','Africa')
,(296,'Kiribati','KI','KIR','Kiribati','Oceania')
,(408,'Korea, Democratic People''s Reworld of','KP','PRK','Choson Minjujuui In�min Konghwaguk (Bukhan)','Asia')
,(410,'Korea, Reworld of','KR','KOR','Taehan Min�guk (Namhan)','Asia')
,(414,'Kuwait','KW','KWT','Al-Kuwayt','Asia')
,(417,'Kyrgyzstan','KG','KGZ','Kyrgyzstan','Asia')
,(418,'Lao People''s Democratic Reworld','LA','LAO','Lao','Asia')
,(428,'Latvia','LV','LVA','Latvija','Europe')
,(422,'Lebanon','LB','LBN','Lubnan','Asia')
,(426,'Lesotho','LS','LSO','Lesotho','Africa')
,(430,'Liberia','LR','LBR','Liberia','Africa')
,(434,'Libya','LY','LBY','Libiya','Africa')
,(438,'Liechtenstein','LI','LIE','Liechtenstein','Europe')
,(440,'Lithuania','LT','LTU','Lietuva','Europe')
,(442,'Luxembourg','LU','LUX','Luxembourg/L�tzebuerg','Europe')
,(446,'Macao','MO','MAC','Macau/Aomen','Asia')
,(807,'Macedonia, the Former Yugoslav Reworld of','MK','MKD','Makedonija','Europe')
,(450,'Madagascar','MG','MDG','Madagasikara/Madagascar','Africa')
,(454,'Malawi','MW','MWI','Malawi','Africa')
,(458,'Malaysia','MY','MYS','Malaysia','Asia')
,(462,'Maldives','MV','MDV','Dhivehi Raajje/Maldives','Asia')
,(466,'Mali','ML','MLI','Mali','Africa')
,(470,'Malta','MT','MLT','Malta','Europe')
,(584,'Marshall Islands','MH','MHL','Marshall Islands/Majol','Oceania')
,(474,'Martinique','MQ','MTQ','Martinique','North America')
,(478,'Mauritania','MR','MRT','Muritaniya/Mauritanie','Africa')
,(480,'Mauritius','MU','MUS','Mauritius','Africa')
,(175,'Mayotte','YT','MYT','Mayotte','Africa')
,(484,'Mexico','MX','MEX','M�xico','North America')
,(583,'Micronesia, Federated States of','FM','FSM','Micronesia','Oceania')
,(498,'Moldova, Reworld of','MD','MDA','Moldova','Europe')
,(492,'Monaco','MC','MCO','Monaco','Europe')
,(496,'Mongolia','MN','MNG','Mongol Uls','Asia')
,(8,'Albania','AL','ALB','Shqip�ria','Europe')
,(500,'Montserrat','MS','MSR','Montserrat','North America')
,(504,'Morocco','MA','MAR','Al-Maghrib','Africa')
,(508,'Mozambique','MZ','MOZ','Mo�ambique','Africa')
,(104,'Myanmar','MM','MMR','Myanma Pye','Asia')
,(516,'Namibia','NA','NAM','Namibia','Africa')
,(520,'Nauru','NR','NRU','Naoero/Nauru','Oceania')
,(524,'Nepal','NP','NPL','Nepal','Asia')
,(528,'Netherlands','NL','NLD','Nederland','Europe')
,(540,'New Caledonia','NC','NCL','Nouvelle-Cal�donie','Oceania')
,(554,'New Zealand','NZ','NZL','New Zealand/Aotearoa','Oceania')
,(558,'Nicaragua','NI','NIC','Nicaragua','North America')
,(562,'Niger','NE','NER','Niger','Africa')
,(566,'Nigeria','NG','NGA','Nigeria','Africa')
,(570,'Niue','NU','NIU','Niue','Oceania')
,(574,'Norfolk Island','NF','NFK','Norfolk Island','Oceania')
,(580,'Northern Mariana Islands','MP','MNP','Northern Mariana Islands','Oceania')
,(578,'Norway','NO','NOR','Norge','Europe')
,(512,'Oman','OM','OMN','�Uman','Asia')
,(586,'Pakistan','PK','PAK','Pakistan','Asia')
,(585,'Palau','PW','PLW','Belau/Palau','Oceania')
,(275,'Palestine, State of','PS','PSE','Filastin','Asia')
,(591,'Panama','PA','PAN','Panam�','North America')
,(598,'Papua New Guinea','PG','PNG','Papua New Guinea/Papua Niugini','Oceania')
,(600,'Paraguay','PY','PRY','Paraguay','South America')
,(604,'Peru','PE','PER','Per�/Piruw','South America')
,(608,'Philippines','PH','PHL','Pilipinas','Asia')
,(612,'Pitcairn','PN','PCN','Pitcairn','Oceania')
,(616,'Poland','PL','POL','Polska','Europe')
,(620,'Portugal','PT','PRT','Portugal','Europe')
,(630,'Puerto Rico','PR','PRI','Puerto Rico','North America')
,(634,'Qatar','QA','QAT','Qatar','Asia')
,(638,'Reunion','RE','REU','R�union','Africa')
,(642,'Romania','RO','ROM','Rom�nia','Europe')
,(643,'Russian Federation','RU','RUS','Rossija','Europe')
,(646,'Rwanda','RW','RWA','Rwanda/Urwanda','Africa')
,(654,'Saint Helena, Ascension and Tristan da Cunha','SH','SHN','Saint Helena','Africa')
,(659,'Saint Kitts and Nevis','KN','KNA','Saint Kitts and Nevis','North America')
,(662,'Saint Lucia','LC','LCA','Saint Lucia','North America')
,(666,'Saint Pierre and Miquelon','PM','SPM','Saint-Pierre-et-Miquelon','North America')
,(670,'Saint Vincent and the Grenadines','VC','VCT','Saint Vincent and the Grenadines','North America')
,(882,'Samoa','WS','WSM','Samoa','Oceania')
,(674,'San Marino','SM','SMR','San Marino','Europe')
,(678,'Sao Tome and Principe','ST','STP','S�o Tom� e Pr�ncipe','Africa')
,(682,'Saudi Arabia','SA','SAU','Al-�Arabiya as-Sa�udiya','Asia')
,(686,'Senegal','SN','SEN','S�n�gal/Sounougal','Africa')
,(690,'Seychelles','SC','SYC','Sesel/Seychelles','Africa')
,(694,'Sierra Leone','SL','SLE','Sierra Leone','Africa')
,(702,'Singapore','SG','SGP','Singapore/Singapura/Xinjiapo/Singapur','Asia')
,(703,'Slovakia','SK','SVK','Slovensko','Europe')
,(705,'Slovenia','SI','SVN','Slovenija','Europe')
,(90,'Solomon Islands','SB','SLB','Solomon Islands','Oceania')
,(706,'Somalia','SO','SOM','Soomaaliya','Africa')
,(710,'South Africa','ZA','ZAF','South Africa','Africa')
,(239,'South Georgia and the South Sandwich Islands','GS','SGS','South Georgia and the South Sandwich Islands','Antarctica')
,(724,'Spain','ES','ESP','Espa�a','Europe')
,(144,'Sri Lanka','LK','LKA','Sri Lanka/Ilankai','Asia')
,(736,'Sudan','SD','SDN','As-Sudan','Africa')
,(740,'Suriname','SR','SUR','Suriname','South America')
,(744,'Svalbard and Jan Mayen','SJ','SJM','Svalbard og Jan Mayen','Europe')
,(748,'Swaziland','SZ','SWZ','kaNgwane','Africa')
,(752,'Sweden','SE','SWE','Sverige','Europe')
,(756,'Switzerland','CH','CHE','Schweiz/Suisse/Svizzera/Svizra','Europe')
,(760,'Syrian Arab Reworld','SY','SYR','Suriya','Asia')
,(158,'Taiwan (Province of China)','TW','TWN','T�ai-wan','Asia')
,(762,'Tajikistan','TJ','TJK','To�ikiston','Asia')
,(834,'Tanzania, United Reworld of','TZ','TZA','Tanzania','Africa')
,(764,'Thailand','TH','THA','Prathet Thai','Asia')
,(768,'Togo','TG','TGO','Togo','Africa')
,(772,'Tokelau','TK','TKL','Tokelau','Oceania')
,(776,'Tonga','TO','TON','Tonga','Oceania')
,(780,'Trinidad and Tobago','TT','TTO','Trinidad and Tobago','North America')
,(788,'Tunisia','TN','TUN','Tunis/Tunisie','Africa')
,(792,'Turkey','TR','TUR','T�rkiye','Asia')
,(795,'Turkmenistan','TM','TKM','T�rkmenostan','Asia')
,(796,'Turks and Caicos Islands','TC','TCA','The Turks and Caicos Islands','North America')
,(798,'Tuvalu','TV','TUV','Tuvalu','Oceania')
,(800,'Uganda','UG','UGA','Uganda','Africa')
,(804,'Ukraine','UA','UKR','Ukrajina','Europe')
,(784,'United Arab Emirates','AE','ARE','Al-Imarat al-�Arabiya al-Muttahida','Asia')
,(826,'United Kingdom','GB','GBR','United Kingdom','Europe')
,(840,'United States','US','USA','United States','North America')
,(581,'United States Minor Outlying Islands','UM','UMI','United States Minor Outlying Islands','Oceania')
,(858,'Uruguay','UY','URY','Uruguay','South America')
,(860,'Uzbekistan','UZ','UZB','Uzbekiston','Asia')
,(548,'Vanuatu','VU','VUT','Vanuatu','Oceania')
,(862,'Venezuela','VE','VEN','Venezuela','South America')
,(704,'Viet Nam','VN','VNM','Vi�t Nam','Asia')
,(92,'Virgin Islands (British)','VG','VGB','British Virgin Islands','North America')
,(850,'Virgin Islands (U.S.)','VI','VIR','Virgin Islands of the United States','North America')
,(876,'Wallis and Futuna','WF','WLF','Wallis-et-Futuna','Oceania')
,(732,'Western Sahara','EH','ESH','As-Sahrawiya','Africa')
,(887,'Yemen','YE','YEM','Al-Yaman','Asia')
,(894,'Zambia','ZM','ZMB','Zambia','Africa')
,(716,'Zimbabwe','ZW','ZWE','Zimbabwe','Africa')
,(4,'Afghanistan','AF','AFG','Afganistan/Afqanestan','Asia')
,(12,'Algeria','DZ','DZA','Al-Jaza�ir/Alg�rie','Africa')
;